Incomplete week-5 assessment. Need to do JS challenges and Jest tests.
learn-academy-2022-echo/week-5-assessment-jayaries329 pull request #1
Opened 2022-09-06 22:33 UTC by jayaries329

# Submitting Week 5 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ ] JavaScript Coding Challenges
- [x] Ruby Coding Challenges
- [x] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2022-09-08 07:47 UTC, jayaries329 commented
JS challenges and Jest tests have been submitted

2022-09-09 16:16 UTC, merged

2022-09-09 19:35 UTC, SunkissedQueen requested changes
Jason, I can complete this assessment after you add the following:

- Test, pseudocode, function for challenge question 3
- pedal_faster and brake method for ruby challenge 3B

2022-09-09 19:35 UTC, SunkissedQueen commented on code-challenges.test.js
> +        } if (value === 'e' || value === 'E') {
good work. Best practices is to have one `if` statement, one `else` statement, and as many `else if` statements as necessary. The `else if` statements are written in the middle. We begin with the `if`. It is optional to have an `else`, but when you do, the `else` will be the last statement.

2022-09-09 19:35 UTC, SunkissedQueen commented on code-challenges.test.js
> +// Return edited, shorter array
Remember input, expected output, and what you are accessing to move from the input to the output

2022-09-09 19:35 UTC, SunkissedQueen commented on interview-questions.md
> +Hashes can also be look at as dictionaries because they perform like them. The term iterate and its definition are an example of a hash:
Cool. More content can be sharing ruby hash to support this dictionary connection

2022-09-09 19:35 UTC, SunkissedQueen commented on interview-questions.md
> +Throughout our challenges over this past week of the cohort, we were using Ruby on Rails packages as we were creating models, working with schemas, and running migrations in our database manipulation
more content can be to state a ruby gem that you use and talk about what it added to the application

2022-09-09 19:35 UTC, SunkissedQueen commented on interview-questions.md
> +Ruby on Rails is an MVC (Model, View, Controller) based framework and it gives a developer a different perspective of an application. Development in Rails is occurring on the backend side and it's da
more content can be to share how M, V, an C delivers that experience

2022-09-09 19:35 UTC, SunkissedQueen commented on interview-questions.md
> +An active example of a relational database in use would be Amazon. The logisitics of Amazon's business thrives on using relational databases to complete orders by simply matching customer's informati
good content here. More things you can share are brief definitions of the 4 other databases you mentioned.

2022-09-09 19:35 UTC, SunkissedQueen commented on interview-questions.md
> +
I understand what is being said. Please consider that rails automatically gives the primary key (PK). So make sure that you are mentioning that when discussing PK. Content that you can add would be a table that shows the primary key as a column.

2022-09-09 19:35 UTC, SunkissedQueen commented on ruby-challenges.rb
>  # -------------------3b) Add the ability to pedal faster and brake. The pedal_faster method should increase the speed by a given amount. The brake method should decrease the speed by a given amount.
Looks like you are missing the pedal_faster and brake methods